module.exports = {
	REQUEST_TOO_FAST: 'REQUEST_TOO_FAST',
	INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
	REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
	ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

	URL_NOT_FOUND: 'URL_NOT_FOUND',

	UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};