module.exports = {
	REQUEST_TOO_FAST: 'REQUEST_TOO_FAST',
	INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
	REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
	ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
	BAD_RESPONSE_STATUS: 'BAD_RESPONSE_STATUS',
	URL_NOT_FOUND: 'URL_NOT_FOUND',

	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	RATE_LIMITED: 'RATE_LIMITED',

	WRONG_INPUT: 'WRONG_INPUT',

	INVALID_JSON: 'INVALID_JSON'
};